version: '2'
services:
    database:
        image: mysql:5.7
        container_name: wie_mysql
        restart: always    
        environment: 
            MYSQL_ROOT_PASSWORD: 'nopassword'
        ports:
            - 3306:3306
        volumes: 
            - wie-mysql-datavolume:/var/lib/mysql
    migration:
        build: .
        links: 
            - database
        environment: 
            MYSQL_USERNAME: root
            MYSQL_HOST: database
            MYSQL_PASSWORD: 'nopassword'
            MYSQL_DATABASE: wordnet
volumes:
    wie-mysql-datavolume: